PennyLaneAI/pennylane-cirq

- .github/CHANGELOG.md
- .travis.yml
- doc/installing.rst
- pennylane_cirq/_version.py
- requirements.txt
- tests/test_apply.py
- tests/test_cirq_device.py
Bump the version to 0.2.0-dev and introduce a changelog
Fix errors introduced by Cirq going from 0.5.0 to 0.6.0
> [WIP] Bump version and adjust to Cirq 0.6.0

- pennylane_cirq/cirq_device.py
- pennylane_cirq/cirq_interface.py
- pennylane_cirq/simulator_device.py
- tests/test_cirq_device.py
- tests/test_cirq_interface.py
This PR adds support to inverse operations to Pennylane-Cirq.
To achieve this, the class `CirqOperation` got a new method `.inv()` which uses `cirq.inverse`. All inverse operations are added to an `_inverse_operation_map` during init and apply just accesses `_complete_operation_map = _operation_map + _inverse_operation_map`.
> Add support for inverse operations

- tests/test_apply.py
This PR changes one of the error messages for the test on unitary matrices. This is required as with `Cirq 0.7` the output has been changed.
> Changing the error message that is outputted for non-unitary matrices

- .github/CHANGELOG.md
- pennylane_cirq/_version.py
- pennylane_cirq/cirq_device.py
- requirements.txt
The following changes were carried out in this PR:
* Increase version number in CHANGELOG
* Update the PR list  in CHANGELOG
* Increase version in `_version.py`
* Increment `pennylane_requires` for the device and in `requirements.txt` since inverses have been added in PennyLane `v0.7` (therefore almost the entire test suite now fails with `v0.6`.
> Increasing the version number to 0.8.0

- pennylane_cirq/simulator_device.py
- tests/test_simulator_device.py
This change follows-up the change in the structure of `QubitDevice`:
https://github.com/XanaduAI/pennylane/pull/573
> Rename probability to analytic_probability

- doc/devices/mixed_simulator.rst
- doc/devices/simulator.rst
- doc/index.rst
- pennylane_cirq/__init__.py
- pennylane_cirq/cirq_device.py
- pennylane_cirq/cirq_interface.py
- pennylane_cirq/cirq_operation.py
- pennylane_cirq/ops.py
- pennylane_cirq/simulator_device.py
- setup.py
- tests/conftest.py
- tests/test_apply.py
- tests/test_cirq_device.py
- tests/test_cirq_interface.py
- tests/test_cirq_operation.py
- tests/test_expval.py
- tests/test_mixed_simulator_device.py
- tests/test_native_ops.py
- tests/test_sample.py
- tests/test_simulator_device.py
- tests/test_var.py
Adds a new `"cirq.mixedsimulator"` class to Cirq, which uses Cirq's `DensityMatrixSimulator` as a backend. Added a number of new ops which can only run on this device.
Also undertook a bit of general clean up while I was working in the repo.
Open questions I came across while working on this. Any thoughts are appreciated.
1. Why are state initialization ops only supported in analytic mode? As far as I can tell, these could still be supported in "non-analytic" mode
2. There is a comment indicating a discrepency between the `state` method returned by `default.qubit` and this plugin. I'm not sure why they weren't brought into alignment
3. ``test_sample_values_hermitian_multi_qubit`` in `test_samples.py` is dependent on the rng seed (if you add more tests, it can cause this one to fail). …
> Adding Cirq DensityMatrixSimulator device

- pennylane_cirq/__init__.py
- pennylane_cirq/cirq_device.py
- pennylane_cirq/pasqal_device.py
- requirements.txt
- setup.py
Adds a new device "cirq.pasqal", which uses the `cirq.pasqal.PasqalDevice` simulator as the execution backend. Cirq should be installed from the following fork: https://github.com/lhenriet/Cirq
Notes
-----
- Pasqal devices require `ThreeDGridQubit`s, which are qubits which have positions in three dimensions.
- Based on reading the plugin code, there are a number of places where an implicit assumption is made that the qubits are `LineQubit`:
- in initialization of cirq_device.py
- in _apply_basis_state in simulator_device.py
- in _apply_qubit_state_vector in simulator_device.py
- in apply in simulator_device.py
- It should be relatively straightforward to allow other qubit types (e.g., `GridQubit` or the `ThreeDGridQubit`s needed for the `PasqalDevice`, but it would require some small …
> [WIP] Add pasqal device

- pennylane_cirq/cirq_device.py
- pennylane_cirq/simulator_device.py
This PR adds some items missing in the wires refactor PR #37  :
- update some device docstrings
- update required PL version
- delete superfluous (and in fact wrong) line in analytic_probabilities
> Some more polishing of the wires refactor

- CHANGELOG.md
- pennylane_cirq/cirq_device.py
- pennylane_cirq/simulator_device.py
- tests/test_cirq_device.py
This PR contains the pasqal-independent bug fixes from #40 by @co9olguy
> Fixes for device wire handling

- pennylane_cirq/__init__.py
- setup.py
- tests/test_qsim_device.py
- tests/test_qsimh_device.py
Removes the import of `qsimcirq` from the `__init__.py` file and fixes the tests and entrypoints to import qsimcirq correctly.
This avoids users having to install `qsimcirq` for the other Cirq devices to work.
> Remove import of qsimcirq from `__init__`

- CHANGELOG.md
- pennylane_cirq/_version.py
Incrementing the version number of the Cirq plugin to 0.13.0.
> bump version to 0.13.0

- .github/workflows/tests.yml
- CHANGELOG.md
- pennylane_cirq/cirq_device.py
- requirements.txt
- tests/test_expval.py
- tests/test_sample.py
- tests/test_var.py
Context:
Adding a projector observable to CirqDevice.
Description of the Change:
Implementing projector observable with Cirq's own ```cirq.ProductState.projector``` method.
Related GitHub PR:
Work coherently with PR [#1356](https://github.com/PennyLaneAI/pennylane/pull/1356)
> Add a projector observable to CirqDevice

- CHANGELOG.md
- pennylane_cirq/simulator_device.py
This data type change should fix the bug appearing when building the density matrix for `QubitStateVector`.
> Fix bug for mixed simulator

- requirements.txt
- setup.py
Update the requirement of PennyLane to point to the release candidate for now, which has a PennyLane version of 0.16.0 as opposed to 0.17.0-dev on `master`.
This is required to be able to run the demos in the QML repo, see e.g., https://github.com/PennyLaneAI/qml/pull/288.
> Update requirements to point to release candidate

- requirements.txt
- tests/test_apply.py
This change was required due to an updated error message in PennyLane core from https://github.com/PennyLaneAI/pennylane/pull/1439
> Update `qml.QubitUnitary` error message in test

- CHANGELOG.md
- README.rst
- requirements.txt
- setup.py
- tests/test_qsim_device.py
- tests/test_qsimh_device.py
- tests/test_sample.py
- tests/test_simulator_device.py
We temporarily require `Cirq<0.12.0` because of broken interaction between the `cirq`0.12.0 and `qsim` 0.10.0.
> Temporary requirement `Cirq<0.12.0`

- tests/test_mixed_simulator_device.py
The recent refractor of the `Operator` class made the use of `num_params` impossible before constructing the operation, therefore a test that builds random circuit has to be changed.
> Fix test for `num_param` refractor

- pennylane_cirq/cirq_device.py
The operator refactor in PennyLane removed an obsolete legacy attribute `string_for_inverse`, which was set to `".inv"` everywhere and only used in one place in the core code.
However, the cirq device uses it in one place. Replacing it with `".inv"` should make the device compatible with the refactor, and have no downsides. While this is not urgent for the upcoming release, it would be easy to merge it in asap.
**Changes** 
Replace attribute call with fixed string.
Three minor improvements to pacify codefactor on unrelated issues, which are picked up in the latest version of the standard.
> [OpRefactor] Fix inverses

- pennylane_cirq/qsim_device.py
- pennylane_cirq/simulator_device.py
- tests/conftest.py
- tests/test_apply.py
- tests/test_cirq_device.py
- tests/test_cirq_operation.py
- tests/test_expval.py
- tests/test_mixed_simulator_device.py
- tests/test_qsim_device.py
- tests/test_qsimh_device.py
- tests/test_sample.py
- tests/test_simulator_device.py
The bug was in the test `test_qsim_device.py:TestSample:test_sample_dimensions`. When `qsim_device.generate_sampels()` is called, it augments the circuit in order to make the measurements. The bug was introduced when this method is called repeatedly without performing a reset `qsim_device.reset()` between calls.
> Bug when trying to generate_samples() repeatedly

- requirements.txt
- setup.py
Installing `cirq` pulls in packages that are not used by this plugin, but packages that bring further dependency constraints.
Pulling `cirq-core` only along with `cirq-pasqal` should provide a solution.
This is useful for the QML repository, where a dependency conflict arises between `cirq-rigetti` and TensorFlow:
```
The conflict is caused by:
tensorflow 2.6.0 depends on six~=1.15.0
cirq-rigetti 0.13.1 depends on six~=1.16.0
```
With the changes here, we'll no longer be requiring `cirq-rigetti`.
> Get cirq-core only

- pennylane_cirq/simulator_device.py
- requirements.txt
- tests/test_mixed_simulator_device.py
- tests/test_native_ops.py
When calling the `simulator.simulate(circuit)` method for `cirq.DensityMatrixSimulator()` simulator (and all mixed state simulators I assume), the kwarg `initial_state=None` was previously passed as a state vector. Now it is required that this quantity be passed as a density matrix. 
The unit tests were updated to make use of this functionality. No other changes required
> Cirq changed `initial_state` kwarg to be density matrix

- .github/workflows/tests.yml
same as PennyLane: https://github.com/PennyLaneAI/pennylane/blob/1e5083d1e549791cf4be140013701c1e026644eb/.github/workflows/tests.yml#L417
CI won't pass, this might be why.
> Update tests.yml to use codecov-v3

- .github/workflows/tests.yml
- .github/workflows/upload.yml
- CHANGELOG.md
- README.rst
- setup.py
This PR adds Python 3.10 tests and removes Python 3.7.  Python 3.11 is not yet added as `qsimcirq` does not yet support Python 3.11.
> Remove Python 3.7, add Python 3.10

- .github/workflows/post_release_version_bump.yml
- .github/workflows/pre_release_version_bump.yml
- CHANGELOG.md
- requirements.txt
- setup.py
fixing the changelog and requiring PL master. This is necessary because this release of pennylane_cirq uses `StatePrep.state_vector` which will be introduced in 0.29.
> add PR link to changelog; require PL master

- pennylane_cirq/_version.py
just realized post-release was missed after 0.28, despite me manually making the changelog update in a previous PR! anyway - this is all that is missing for 0.29 to be release-ready now.
example of previous pre-release: #128 
changelog for this release added in #130 (first commit there)
> manual pre-release 0.29 updates

- requirements.txt
- setup.py
The plugin-test-matrix is [currently failing](https://github.com/PennyLaneAI/plugin-test-matrix/actions?query=workflow%3Acirq-latest-rc) because this plugin is using pennylane master, which now has the version attribute set to `0.30.0.dev0` but it expects the version to be `0.29.0` (which it would be on the RC branch)
> pin versions to 0.29 rc branch

- requirements.txt
- setup.py
This reverts commit 4279e4baa2a1456007b3d90d64c70ecde7ff9ddd.
This change [broke qml](https://github.com/PennyLaneAI/qml/actions/runs/4256059628/jobs/7404470521)! Undo now that we are comfortable with plugin tests passing.
PS: the plugin tests [passed](https://github.com/PennyLaneAI/plugin-test-matrix/actions/runs/4256199317/jobs/7404766576) while this PR was not yet merged :)
> Revert "pin versions to 0.29 rc branch (#135)"

- CHANGELOG.md
- requirements.txt
This PR fixes the changelog for an accidental push to master: https://github.com/PennyLaneAI/pennylane-cirq/commit/2ae8c3921ad437a95bd4543fdd6690eee263abf8
Basically, we just need to bump the PL requires version to 0.29.0
> Version bump

- tests/test_mixed_simulator_device.py
this test was halfway-fixed to stop using the `analytic` keyword once upon a time, but the `False` was accidentally left behind. With the new validation (introduced in PennylaneAI/pennylane#4169) in `_device.py` when setting shots, this failed suddenly!
> fix test to not fail with new shots validation

- tests/test_mixed_simulator_device.py
- tests/test_qsim_device.py
- tests/test_qsimh_device.py
- tests/test_sample.py
- tests/test_simulator_device.py
- tests/test_var.py
The `do_queue` argument has been removed from PennyLane. Here we remove `do_queue=False` from the tests for the plugin.
> Remove do queue

- .github/workflows/format.yml
- .github/workflows/tests.yml
- .readthedocs.yaml
- CHANGELOG.md
- README.rst
- doc/requirements.txt
- pennylane_cirq/cirq_device.py
- pennylane_cirq/qsim_device.py
- pennylane_cirq/simulator_device.py
- setup.py
- tests/test_apply.py
- tests/test_mixed_simulator_device.py
- tests/test_qsim_device.py
- tests/test_qsimh_device.py
- tests/test_simulator_device.py
The CI was experiencing some failures: https://github.com/PennyLaneAI/plugin-test-matrix/actions/runs/5930704451/job/16080993219?pr=46
but updating to natively support `StatePrep` as well as `QubitStateVector` seems to fix the problem.
> Add `StatePrep` support

- pennylane_cirq/simulator_device.py
- tests/test_mixed_simulator_device.py
With numpy <1.25, the probs are identical (`[0.49999967, 0.49999967]`) before dotting with the eigenvalues so the result is exactly zero. With numpy >=1.25, they are not (`[0.49999964, 0.49999958]`). This slight change is very mysterious to me, but I have confirmed that it appears at [this line](https://github.com/PennyLaneAI/pennylane-cirq/blob/8447c1116355de8390789c2cb7794fa6deab50fd/pennylane_cirq/simulator_device.py#L109-L111). The inputted `self.circuit` is identical, and the outputted result is reliably off. Each value in the state is off by up to 3e-8, and I don't know why (they aren't totally random rounding errors because the difference between old and new states are numbers like `1.00000e-8` or `9.3400000e-9`).
My solution for now is to allow an atol of 5e-8.
EDIT: I've removed …
> remove expval ovverride; allow atol for cirq mixed state simulator test

- .github/workflows/tests.yml
- CHANGELOG.md
- doc/devices/pasqal.rst
- pennylane_cirq/cirq_device.py
- pennylane_cirq/pasqal_device.py
- tests/test_pasqal_device.py
`cirq.Circuit` no longer has a device argument.
This wasn't caught as the reset method was not being tested for the pasqal device.  This PR also adds a test that will execute multiple circuits.
I also started converting `control_radius` to a float so we can start using `cirq.pasqal` in the automatic test matrix.
> Fix batch execute with pasqal device

- .github/workflows/tests.yml
Pennylane tests now require the pytest-benchmarks package.
> Add pytest-benchmark to test requirements

- CHANGELOG.md
- tests/test_sample.py
Tests in `test_sample.py` are setting an `_obs_queue` property and setting the return type of the observable.  
This private property might be a legacy holdover from several years ago. It does nothing at this current point in time.
So I'm simply removing them from the tests.
> remove unnecessary `_obs_queue` property

- doc/index.rst
Some image links were not working correctly after the QML repo restructuring:
This PR fixes these URLs so they point to the right place
> Fix image urls to point to new image locations

- doc/requirements.txt
- requirements.txt
Bump cirq to version 1.3.0 in the `requirements.txt` files, and bump all the other things that need to be bumped to make that work.
> Try bumping cirq_core

- .github/workflows/tests.yml
- pennylane_cirq/cirq_device.py
- pennylane_cirq/pasqal_device.py
- pennylane_cirq/qsim_device.py
- pennylane_cirq/simulator_device.py
- tests/test_mixed_simulator_device.py
- tests/test_native_ops.py
- tests/test_pasqal_device.py
- tests/test_qsim_device.py
- tests/test_qsimh_device.py
- tests/test_sample.py
- tests/test_simulator_device.py
- tests/test_var.py
Add support for Prod observable.
[sc-60542]
> Add prod support to cirq device

- pennylane_cirq/cirq_device.py
**Context**
`apply` fails with `Identity` on multiple wires because `cirq.I` only accepts a single wire.
**Change**
Replace `cirq.I` with `cirq.IdentityGate` which does allow specifying the number of wires
**Shortcut**
[sc-61681]
> BugFix: support for Identity on multiple wires

- pennylane_cirq/cirq_device.py
pennylane.QubitDevice is deprecated in v0.39, importing QubitDevice from pennylane.devices instead.
> Fix deprecated import path for `QubitDevice`

- pennylane_cirq/qsim_device.py
- pennylane_cirq/simulator_device.py
- tests/test_mixed_simulator_device.py
`pennylane.QubitDevice` has been deprecated as of PennyLane v0.39. This PR ensures that `QubitDevice` is now imported from `pennylane.devices` instead.
This PR is a followup to https://github.com/PennyLaneAI/pennylane-cirq/pull/194 where some of these changes seem to have been overlooked.
> Replace qml.QubitDevice with qml.devices.QubitDevice

- pennylane_cirq/simulator_device.py
`Tensor` is deprecated, remove its use from code.
> Remove deprecated use of `Tensor`

- CHANGELOG.md
- doc/devices/qsim.rst
- pennylane_cirq/cirq_device.py
- pennylane_cirq/qsim_device.py
- pennylane_cirq/simulator_device.py
- tests/test_apply.py
- tests/test_mixed_simulator_device.py
- tests/test_simulator_device.py
**Context:**
Completing the deprecation cycle of `QubitStateVector` (see https://github.com/PennyLaneAI/pennylane/pull/6525)
**Description of the Change:**
Removed all references to the deprecated source code.
[sc-77482]
> Delete references to the removed `QubitStateVector` class

- CHANGELOG.md
- pennylane_cirq/_version.py
Post-release version bump.
**DO NOT MERGE**
It should be merged *after* the plugin has been released.
> Post-release version bump

- .github/workflows/tests.yml
- .github/workflows/upload.yml
- CHANGELOG.md
- pennylane_cirq/_version.py
**Context:**
`setuptools` has had a release recently that normalizes package names:
References:
- pypa/setuptools#4766
- https://packaging.python.org/en/latest/specifications/name-normalization/#name-normalization
**Description of the Change:**
Due setuptools 75.8.0 and 75.8.1 outputting completely different package names, we cannot support both, so CI now "pins" to >=75.8.1.
**Benefits:**
Fix CI failures.
[sc-85704]
> Updating `setuptools`

- .github/workflows/upload.yml
`pip install cirq` is broken for Python3.10 due to the Rigetti dependency having issues with the CRC of the compiled module.
Therefore, we switch from `Python 3.10` to `Python 3.11` in the `upload` workflow, otherwise we'll likely have issues with the upcoming release of this plugin.
[sc-85836]
> Updating Python version to 3.11 in `upload` workflow

- pennylane_cirq/cirq_device.py
- pennylane_cirq/cirq_operation.py
- pennylane_cirq/simulator_device.py
- tests/test_cirq_device.py
- tests/test_cirq_operation.py
- tests/test_mixed_simulator_device.py
- tests/test_sample.py
- tests/test_simulator_device.py
**Context:**
https://github.com/PennyLaneAI/pennylane/pull/7205 adds the new `exceptions` module.
**Description of the Change:**
Update to use that new module rather than top level imports.
**Benefits:** Should not depend on top-level imports.
**Possible Drawbacks:** None
[sc-88954]
> use new `pennylane.exceptions` module rather than top-level import

- .readthedocs.yaml
- CHANGELOG.md
**Description of the Change:**
Upgrading the readthedocs.yml runner to Ubuntu-24.04 from Ubuntu22.04; 22.04 is in end of life.
**Benefits:**
The readthedocs runner gets upgrade.
**Possible Drawbacks:**
There could be potential compatibility issues with sphinx and other packages. None were found in the PR run.
**Related GitHub Issues:**
> Update ubuntu version to 24.04 in readthedocs.yaml

- CHANGELOG.md
- tests/conftest.py
- tests/test_expval.py
- tests/test_mixed_simulator_device.py
- tests/test_qsim_device.py
- tests/test_qsimh_device.py
- tests/test_simulator_device.py
Besides, added a fixture `device_none_shots` to handle the test suites in `test_expval.py`
[sc-95432]
> Use `set_shots` in tests
